In [1]:
import pandas as pd

df = pd.read_csv("Business licences data.csv")

/var/folders/69/g590bg750s935v88zgfrdm9w0000gn/T/ipykernel_79272/3680689320.py:3: DtypeWarning: Columns (7,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Business licences data.csv")

In [2]:
df_filtered = df[df['Licence Address Line 3'].fillna('').str.startswith('M5T')]
df_filtered.head()

,_id,Category,Licence No.,Operating Name,Issued,Client Name,Business Phone,Business Phone Ext.,Licence Address Line 1,Licence Address Line 2,Licence Address Line 3,Ward,Conditions,Free Form Conditions Line 1,Free Form Conditions Line 2,Plate No.,Endorsements,Cancel Date,Last Record Update
136,137,LIMOUSINE SERVICE COMPANY,B04-3612409,NaN,2006-06-29,"HOY, SIDNEY",NaN,NaN,112 BALDWIN ST,"TORONTO, ON",M5T 1L6,11.0,MAILING ADDRESS ONLY; MUST COMPLY WITH CITY/ZO...,NaN,NaN,NaN,LIMOUSINE SERVICE COMPANY;,2007-09-29,2007-09-29
320,321,LIMOUSINE SERVICE COMPANY,B04-3725390,HIRUY ALEMSEGED WOLDETEKIE,2007-08-02,"WOLDETEKIE, HIRUY ALEMSEGED",NaN,NaN,"96 ST PATRICK ST, #802","TORONTO, ON",M5T 1V2,10.0,MAILING ADDRESS ONLY; MUST COMPLY WITH CITY/ZO...,NaN,NaN,NaN,LIMOUSINE SERVICE COMPANY;,2020-11-03,2020-11-03
368,369,TAXICAB OPERATOR,B05-5000993,NaN,2020-01-06,"NURUDDIN, MOHAMMAD",NaN,NaN,121 VANAULEY WALK,"TORONTO, ON",M5T 2H9,10.0,OFFICE USE ONLY;,NaN,NaN,NaN,TAXICAB OPERATOR;,2020-09-09,2020-09-09
420,421,PRIVATE PARKING ENFORCEMENT AGENCY,B06-3239187,ONTARIO COLLEGE OF ART & DESIGN,2002-07-17,ONTARIO COLLEGE OF ART & DESIGN,NaN,NaN,100 MCCAUL ST,"TORONTO, ON",M5T 1W1,10.0,NaN,NaN,NaN,NaN,PRIVATE PARKING ENFORCEMENT AGENCY;,2005-07-17,2014-09-30
631,632,DRIVING SCHOOL OPERATOR (B),B12-3239159,GOOD LUCK DRIVING SCHOOL,2002-02-15,GOOD LUCK GROUP INC,NaN,NaN,350 DUNDAS ST W,"TORONTO, ON",M5T 1G5,11.0,OFFICE USE ONLY;,"438-86, AS AMENDED",NaN,NaN,D.S.O. - OFFICE - NO VEHICLE;,2005-05-18,2007-07-17

In [3]:
from geopy.geocoders import GoogleV3
import time
from tqdm import tqdm

# Enable tqdm progress bar for pandas operations
tqdm.pandas(desc="Geocoding addresses")

# Initialize Google geocoder with your API key
geocoder = GoogleV3(api_key='AIzaSyAQNLAbA84qUf6jPFgylhphc5roiILaFaA')

# Combine address lines into a single address string
df_filtered = df_filtered.copy()  # Avoid SettingWithCopyWarning
df_filtered['full_address'] = (
    df_filtered['Licence Address Line 1'].fillna('') + ', ' +
    df_filtered['Licence Address Line 2'].fillna('') + ', ' +
    df_filtered['Licence Address Line 3'].fillna('')
).str.strip(', ')

# Geocode the addresses
def geocode_address(address):
    try:
        location = geocoder.geocode(address, timeout=10)
        if location:
            return pd.Series({'latitude': location.latitude, 'longitude': location.longitude})
        else:
            return pd.Series({'latitude': None, 'longitude': None})
    except Exception as e:
        return pd.Series({'latitude': None, 'longitude': None})

# Apply geocoding with progress bar (this may take a while depending on number of addresses)
print(f"Geocoding {len(df_filtered)} addresses...")
df_filtered[['latitude', 'longitude']] = df_filtered['full_address'].progress_apply(geocode_address)
print("Geocoding complete!")

# Display results
df_filtered[['full_address', 'latitude', 'longitude']].head(10)

Geocoding 3662 addresses...

Geocoding addresses: 100%|██████████| 3662/3662 [07:34<00:00,  8.05it/s]

Geocoding complete!

                                        full_address   latitude  longitude
136             112 BALDWIN ST, TORONTO, ON, M5T 1L6  43.655356 -79.397590
320     96 ST PATRICK ST, #802, TORONTO, ON, M5T 1V2  43.653163 -79.390035
368          121 VANAULEY WALK, TORONTO, ON, M5T 2H9  43.650451 -79.399547
420              100 MCCAUL ST, TORONTO, ON, M5T 1W1  43.653184 -79.391484
631            350 DUNDAS ST W, TORONTO, ON, M5T 1G5  43.654163 -79.393003
678      289 SPADINA AVE, #202, TORONTO, ON, M5T 2E6  43.653351 -79.397787
702      310 SPADINA AVE, #206, TORONTO, ON, M5T 2E8  43.653653 -79.398902
847      310 SPADINA AVE, #206, TORONTO, ON, M5T 2E8  43.653653 -79.398902
950      310 SPADINA AVE, #206, TORONTO, ON, M5T 2E8  43.653653 -79.398902
952  310 SPADINA AVE, G12-G13A, TORONTO, ON, M5T 2E8  43.653653 -79.398902

In [4]:
df_filtered.head()

,_id,Category,Licence No.,Operating Name,Issued,Client Name,Business Phone,Business Phone Ext.,Licence Address Line 1,Licence Address Line 2,...,Conditions,Free Form Conditions Line 1,Free Form Conditions Line 2,Plate No.,Endorsements,Cancel Date,Last Record Update,full_address,latitude,longitude
136,137,LIMOUSINE SERVICE COMPANY,B04-3612409,NaN,2006-06-29,"HOY, SIDNEY",NaN,NaN,112 BALDWIN ST,"TORONTO, ON",...,MAILING ADDRESS ONLY; MUST COMPLY WITH CITY/ZO...,NaN,NaN,NaN,LIMOUSINE SERVICE COMPANY;,2007-09-29,2007-09-29,"112 BALDWIN ST, TORONTO, ON, M5T 1L6",43.655356,-79.397590
320,321,LIMOUSINE SERVICE COMPANY,B04-3725390,HIRUY ALEMSEGED WOLDETEKIE,2007-08-02,"WOLDETEKIE, HIRUY ALEMSEGED",NaN,NaN,"96 ST PATRICK ST, #802","TORONTO, ON",...,MAILING ADDRESS ONLY; MUST COMPLY WITH CITY/ZO...,NaN,NaN,NaN,LIMOUSINE SERVICE COMPANY;,2020-11-03,2020-11-03,"96 ST PATRICK ST, #802, TORONTO, ON, M5T 1V2",43.653163,-79.390035
368,369,TAXICAB OPERATOR,B05-5000993,NaN,2020-01-06,"NURUDDIN, MOHAMMAD",NaN,NaN,121 VANAULEY WALK,"TORONTO, ON",...,OFFICE USE ONLY;,NaN,NaN,NaN,TAXICAB OPERATOR;,2020-09-09,2020-09-09,"121 VANAULEY WALK, TORONTO, ON, M5T 2H9",43.650451,-79.399547
420,421,PRIVATE PARKING ENFORCEMENT AGENCY,B06-3239187,ONTARIO COLLEGE OF ART & DESIGN,2002-07-17,ONTARIO COLLEGE OF ART & DESIGN,NaN,NaN,100 MCCAUL ST,"TORONTO, ON",...,NaN,NaN,NaN,NaN,PRIVATE PARKING ENFORCEMENT AGENCY;,2005-07-17,2014-09-30,"100 MCCAUL ST, TORONTO, ON, M5T 1W1",43.653184,-79.391484
631,632,DRIVING SCHOOL OPERATOR (B),B12-3239159,GOOD LUCK DRIVING SCHOOL,2002-02-15,GOOD LUCK GROUP INC,NaN,NaN,350 DUNDAS ST W,"TORONTO, ON",...,OFFICE USE ONLY;,"438-86, AS AMENDED",NaN,NaN,D.S.O. - OFFICE - NO VEHICLE;,2005-05-18,2007-07-17,"350 DUNDAS ST W, TORONTO, ON, M5T 1G5",43.654163,-79.393003

In [5]:
df_filtered.to_csv('geocoded_m5t_licenses.csv', index=False)
print(f"Data saved to geocoded_m5t_licenses.csv ({len(df_filtered)} rows)")

Data saved to geocoded_m5t_licenses.csv (3662 rows)

In [7]:
bld_kensington = pd.read_csv("bld-kensington.csv")
bld_kensington.head()

,_id,Category,Licence No.,Operating Name,Issued,Client Name,Business Phone,Business Phone Ext.,Licence Address Line 1,Licence Address Line 2,...,Conditions,Free Form Conditions Line 1,Free Form Conditions Line 2,Plate No.,Endorsements,Cancel Date,Last Record Update,full_address,latitude,longitude
0,679,DRIVING SCHOOL OPERATOR (B),B12-3364707,KINGSWAY (DOWNTOWN) DRIVING SCHOOL,2003/10/01,1581224 ONTARIO INC,NaN,NaN,"289 SPADINA AVE, #202","TORONTO, ON",...,NaN,NaN,NaN,NaN,D.S.O. - OFFICE - NO VEHICLE;,2006/08/02,2007/07/17,"289 SPADINA AVE, #202, TORONTO, ON, M5T 2E6",43.653351,-79.397787
1,703,DRIVING SCHOOL OPERATOR (B),B12-3121253,TORONTO CENTRAL DRIVING SCHOOL,2001/03/22,PAN AM PACIFIC INC,NaN,NaN,"310 SPADINA AVE, #206","TORONTO, ON",...,NaN,NaN,NaN,NaN,D.S.O. - OFFICE - NO VEHICLE;,2007/04/04,2007/07/17,"310 SPADINA AVE, #206, TORONTO, ON, M5T 2E8",43.653653,-79.398902
2,848,DRIVING SCHOOL OPERATOR (B),B12-3608463,TORONTO CENTRAL DRIVING SCHOOL,2006/04/05,TORONTO CENTRAL DRIVING SCHOOL INC,NaN,NaN,"310 SPADINA AVE, #206","TORONTO, ON",...,NaN,NaN,NaN,NaN,D.S.O. - OFFICE - NO VEHICLE;,2012/10/09,2012/10/09,"310 SPADINA AVE, #206, TORONTO, ON, M5T 2E8",43.653653,-79.398902
3,951,DRIVING SCHOOL OPERATOR (B),B12-4200785,TORONTO CENTRAL DRIVING SCHOOL,2012/10/09,TORONTO CENTRAL TRAINING SCHOOL INC,NaN,NaN,"310 SPADINA AVE, #206","TORONTO, ON",...,NaN,NaN,NaN,NaN,D.S.O. - OFFICE - NO VEHICLE;,2016/07/18,2016/07/18,"310 SPADINA AVE, #206, TORONTO, ON, M5T 2E8",43.653653,-79.398902
4,953,DRIVING SCHOOL OPERATOR (B),B12-3122337,WORLD DRIVING SCHOOL,2001/04/26,WORLD DRIVING SCHOOL INC,NaN,NaN,"310 SPADINA AVE, G12-G13A","TORONTO, ON",...,NaN,NaN,NaN,NaN,D.S.O. - OFFICE - NO VEHICLE;,2016/07/27,2016/07/27,"310 SPADINA AVE, G12-G13A, TORONTO, ON, M5T 2E8",43.653653,-79.398902

In [8]:
print("Column headers:")
print(df_filtered.columns.tolist())

Column headers:
['_id', 'Category', 'Licence No.', 'Operating Name', 'Issued', 'Client Name', 'Business Phone', 'Business Phone Ext.', 'Licence Address Line 1', 'Licence Address Line 2', 'Licence Address Line 3', 'Ward', 'Conditions', 'Free Form Conditions Line 1', 'Free Form Conditions Line 2', 'Plate No.', 'Endorsements', 'Cancel Date', 'Last Record Update', 'full_address', 'latitude', 'longitude']